# Generated by Django 5.1.6 on 2025-03-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='skills/'),
        ),
    ]
