# Generated by Django 5.1.6 on 2025-03-03 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_skill_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='level',
        ),
    ]
